
// 用户页面根据这个配置进行展示 
export const config = {
  className: "com.gccloud.dataroom.core.module.manage.dto.DataRoomPageDTO",
  appCode: "",
  id: "12020",
  name: "演示测试",
  code: "preview_bigScreen_7vgOkzTcCq",
  icon: "00dataSourceSet",
  coverPicture: "",
  iconColor: "#007aff",
  orderNum: 0,
  remark: "",
  style: "",
  parentCode: "bigScreenCatalog_VnfHQk5MOg",
  chartList: [
    {
      className:
        "com.gccloud.dataroom.core.module.chart.components.ScreenTextChart",
      version: "2023111401",
      key: "1719155986688",
      code: "hAznSJey_ieTDA",
      dataSource: {
        className:
          "com.gccloud.dataroom.core.module.chart.components.datasource.DataSetDataSource",
        source: "static",
        businessKey: "990",
        dataSourceKey: "",
        dataSetType: "1",
        params: {},
        dimensionField: "",
        metricField: "",
        seriesField: "",
        dimensionFieldList: [],
        metricFieldList: [],
        seriesFieldList: [],
        serverPagination: false,
        pageSize: 10,
        colorField: null,
        shapeField: null,
        sizeField: null,
      },
      showTitle: true,
      title: "文本",
      name: "文本",
      type: "texts",
      w: 200,
      h: 60,
      x: 1323,
      y: 54,
      z: 4,
      group: "",
      locked: false,
      linkage: {
        action: {
          type: "js",
          script: "",
        },
        components: [],
      },
      inParams: [],
      theme: {
        dark: {
          color: "left,#ffffff,#ffffff",
        },
        light: {
          color: "left,#ffffff,#ffffff",
        },
      },
      border: {
        type: "",
        titleHeight: 60,
        fontSize: 30,
        isTitle: true,
        padding: [0, 0, 0, 0],
      },
      expression: "return ",
      expressionCodes: [],
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      perspective: 0,
      skewX: 0,
      skewY: 0,
      customize: {
        fontSize: 20,
        fontWeight: 700,
        fontFamily: "",
        color: "left,#ffffff,#ffffff",
        title: "周更新：06-13",
        align: "center",
        letterSpacing: 1,
      },
    },
    {
      className:
        "com.gccloud.dataroom.core.module.chart.components.ScreenTextChart",
      version: "2023111401",
      key: "1719155908635",
      code: "hAznSJey",
      dataSource: {
        className:
          "com.gccloud.dataroom.core.module.chart.components.datasource.DataSetDataSource",
        source: "static",
        businessKey: "990",
        dataSourceKey: "",
        dataSetType: "1",
        params: {},
        dimensionField: "",
        metricField: "planHlwdHz",
        seriesField: "",
        dimensionFieldList: [],
        metricFieldList: [],
        seriesFieldList: [],
        serverPagination: false,
        pageSize: 10,
        colorField: null,
        shapeField: null,
        sizeField: null,
      },
      showTitle: true,
      title: "文本",
      name: "文本",
      type: "texts",
      w: 200,
      h: 60,
      x: 986,
      y: 46,
      z: 4,
      group: "",
      locked: false,
      linkage: {
        action: {
          type: "js",
          script: "",
        },
        components: [],
      },
      inParams: [],
      theme: {
        dark: {
          color: "left,#ffffff,#ffffff",
        },
        light: {
          color: "left,#ffffff,#ffffff",
        },
      },
      border: {
        type: "",
        titleHeight: 60,
        fontSize: 30,
        isTitle: true,
        padding: [0, 0, 0, 0],
      },
      expression: "return ",
      expressionCodes: [],
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      perspective: 0,
      skewX: 0,
      skewY: 0,
      customize: {
        fontSize: 20,
        fontWeight: 700,
        fontFamily: "",
        color: "left,#ffffff,#ffffff",
        title: "T+3计划合理性",
        align: "center",
        letterSpacing: 1,
      },
    },
    {
      className:
        "com.gccloud.dataroom.core.module.chart.components.CustomComponentChart",
      version: "2023111501",
      key: "dPcMkbCF",
      code: "dPcMkbCF",
      dataSource: {
        className:
          "com.gccloud.dataroom.core.module.chart.components.datasource.DataSetDataSource",
        source: "dataset",
        businessKey: "",
        dataSourceKey: "",
        dataSetType: "1",
        params: {},
        dimensionField: "",
        metricField: "",
        seriesField: "",
        dimensionFieldList: [],
        metricFieldList: [],
        seriesFieldList: [],
        serverPagination: false,
        pageSize: 10,
        colorField: null,
        shapeField: null,
        sizeField: null,
      },
      showTitle: true,
      title: "分组柱状图",
      name: "FenZuZhuZhuangTu",
      type: "customComponent",
      w: 533,
      h: 339,
      x: 990,
      y: 105,
      z: 3,
      group: "",
      locked: false,
      linkage: {
        action: {
          type: "js",
          script: "",
        },
        components: [],
      },
      inParams: [],
      theme: {
        dark: {
          label_style_fill: "#ffffff",
          color: ["#6b74e4", "#4391f4", "#38bbe5", "#69d6fd", "#36c6a0"],
          yAxis_grid_line_style_stroke: "#E5E6EB10",
          legendItemName_style_fill: "#e9e9e9",
          xAxis_title_style_fill: "#e9e9e9",
          xAxis_label_style_fill: "#e9e9e9",
          xAxis_line_style_stroke: "#C9CDD4",
          xAxis_tickLine_style_stroke: "#C9CDD4",
          yAxis_title_style_fill: "#e9e9e9",
          yAxis_label_style_fill: "#e9e9e9",
          yAxis_line_stroke: "#C9CDD4",
        },
        light: {
          label_style_fill: "#ffffff",
          color: ["#6b74e4", "#4391f4", "#38bbe5", "#69d6fd", "#36c6a0"],
          yAxis_grid_line_style_stroke: "#E5E6EB10",
          legendItemName_style_fill: "#e9e9e9",
          xAxis_title_style_fill: "#e9e9e9",
          xAxis_label_style_fill: "#e9e9e9",
          xAxis_line_style_stroke: "#C9CDD4",
          xAxis_tickLine_style_stroke: "#C9CDD4",
          yAxis_title_style_fill: "#e9e9e9",
          yAxis_label_style_fill: "#e9e9e9",
          yAxis_line_stroke: "#C9CDD4",
        },
      },
      border: {
        type: "",
        titleHeight: 60,
        fontSize: 16,
        isTitle: true,
        padding: [16, 16, 16, 16],
      },
      expression: null,
      expressionCodes: null,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      perspective: 0,
      skewX: 0,
      skewY: 0,
      parentCode: null,
      optionHandler:
        "\noption.legend = option.legendEnable ? {position: setting.find(settingItem=>settingItem.field === 'legendPosition').value} : false;\nif (option.legendEnable) {\n  option.legend.itemName = option.legendItemName\n};\noption.yAxis.grid.line.style.lineDash = [4,setting.find(settingItem=>settingItem.field === 'yAxis_grid_line_style_lineDash').value]\nlet autoHide = setting.find(settingItem=>settingItem.field === 'xAxis_label_autoHide').value\nif(autoHide){\n  let minGap = option.xAxis.label.autoHideMinGap\n  option.xAxis.label.autoHide = {\n    type: 'equidistance',\n    cfg: { minGap: minGap }\n  }\n} else {\n  option.xAxis.label.autoHide = false\n}\n  ",
      dataHandler: "",
      chartType: "Column",
      option:
        '{"dataKey":"data","appendPadding":[0,0,0,0],"renderer":"canvas","data":[],"legendEnable":false,"legendLayout":"vertical","legendPosition":"top","legendItemName":{"style":{"fill":"#e9e9e9","fontSize":12,"fontWeight":400}},"legend":false,"color":["#6b74e4","#4391f4","#38bbe5","#69d6fd","#36c6a0"],"isGroup":true,"xField":"date","yField":"value","seriesField":"type","pattern":{"type":""},"xAxis":{"title":{"text":"","position":"end","style":{"fill":"#e9e9e9","fontSize":12}},"label":{"autoRotate":true,"autoHide":{"type":"equidistance","cfg":{"minGap":0}},"autoEllipsis":true,"autoHideEnable":true,"autoHideMinGap":0,"style":{"fill":"#e9e9e9","fontSize":12}},"line":{"style":{"stroke":"#C9CDD4","lineWidth":1}},"tickLine":{"style":{"stroke":"#C9CDD4","lineWidth":1}}},"yAxis":{"title":{"text":"","position":"end","autoRotate":true,"style":{"fill":"#e9e9e9","fontSize":12}},"grid":{"line":{"style":{"stroke":"#E5E6EB10","lineWidth":1,"lineDash":[4,0],"strokeOpacity":0.7}}},"label":{"formatter":"(function(e){return e<1e3?e:e>=1e3&&e<1e6?\\"\\".concat(e).replace(/\\\\d{1,3}(?=(\\\\d{3})+$)/g,(function(e){return\\"\\".concat(e,\\",\\")})):e>=1e6&&e<1e9?\\"\\".concat((e/1e6).toFixed(1),\\" M\\"):\\"\\".concat((e/1e9).toFixed(1),\\" B\\")})","style":{"fill":"#e9e9e9","fontSize":12,"opacity":1}},"line":{"style":{"stroke":"#C9CDD4","lineWidth":0}}},"label":{"offsetY":20,"position":"middle","style":{"fill":"#ffffff","opacity":0,"fontSize":10}},"displayOption":{"serverPagination":{"enable":false},"pageSize":{"enable":false},"metricField":{"label":"指标","enable":true,"multiple":true},"dimensionField":{"label":"维度","enable":true,"multiple":true},"dimensionList":{"label":"维度","enable":false,"multiple":true},"seriesField":{"enable":false,"required":true},"dataAllocation":{"enable":true},"params":{"enable":true},"dataSourceType":{"enable":true}},"theme":"transparent"}',
      setting: [
        {
          field: "xField",
          value: "",
        },
        {
          field: "yField",
          value: "",
        },
        {
          field: "seriesField",
          value: "",
        },
        {
          field: "label_style_opacity",
          value: 0,
        },
        {
          field: "label_position",
          value: "middle",
        },
        {
          field: "label_style_fill",
          value: "#ffffff",
        },
        {
          field: "label_style_fontSize",
          value: 10,
        },
        {
          field: "color",
          value: ["#6b74e4", "#4391f4", "#38bbe5", "#69d6fd", "#36c6a0"],
        },
        {
          field: "yAxis_grid_line_style_lineDash",
          value: 0,
        },
        {
          field: "yAxis_grid_line_style_lineWidth",
          value: 1,
        },
        {
          field: "yAxis_grid_line_style_stroke",
          value: "#E5E6EB10",
        },
        {
          field: "legendEnable",
          value: false,
        },
        {
          field: "legendPosition",
          value: "top",
        },
        {
          field: "legendItemName_style_fontSize",
          value: 12,
        },
        {
          field: "legendItemName_style_fontWeight",
          value: 400,
        },
        {
          field: "legendItemName_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "xAxis_title_text",
          value: "",
        },
        {
          field: "xAxis_title_position",
          value: "end",
        },
        {
          field: "xAxis_title_style_fontSize",
          value: 12,
        },
        {
          field: "xAxis_title_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "xAxis_label_style_fontSize",
          value: 12,
        },
        {
          field: "xAxis_label_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "xAxis_line_style_lineWidth",
          value: 1,
        },
        {
          field: "xAxis_line_style_stroke",
          value: "#C9CDD4",
        },
        {
          field: "xAxis_tickLine_style_lineWidth",
          value: 1,
        },
        {
          field: "xAxis_tickLine_style_stroke",
          value: "#C9CDD4",
        },
        {
          field: "xAxis_label_autoHide",
          value: true,
        },
        {
          field: "xAxis_label_autoHide_minGap",
          value: 0,
        },
        {
          field: "xAxis_label_autoRotate",
          value: true,
        },
        {
          field: "xAxis_label_autoEllipsis",
          value: true,
        },
        {
          field: "yAxis_title_text",
          value: "",
        },
        {
          field: "yAxis_title_autoRotate",
          value: true,
        },
        {
          field: "yAxis_title_position",
          value: "end",
        },
        {
          field: "yAxis_title_style_fontSize",
          value: 12,
        },
        {
          field: "yAxis_title_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "yAxis_label_style_opacity",
          value: 1,
        },
        {
          field: "yAxis_label_style_fontSize",
          value: 12,
        },
        {
          field: "yAxis_label_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "yAxis_line_lineWidth",
          value: 0,
        },
        {
          field: "yAxis_line_stroke",
          value: "#C9CDD4",
        },
        {
          field: "appendPadding",
          value: [0, 0, 0, 0],
        },
      ],
      category: "分组柱状图",
    },
    {
      className:
        "com.gccloud.dataroom.core.module.chart.components.ScreenTextChart",
      version: "2023111401",
      key: "1719155696650",
      code: "hiDKMQzy_QXnRR",
      dataSource: {
        className:
          "com.gccloud.dataroom.core.module.chart.components.datasource.DataSetDataSource",
        source: "static",
        businessKey: "991",
        dataSourceKey: "",
        dataSetType: "1",
        params: {},
        dimensionField: "",
        metricField: "runDt",
        seriesField: "",
        dimensionFieldList: [],
        metricFieldList: [],
        seriesFieldList: [],
        serverPagination: false,
        pageSize: 10,
        colorField: null,
        shapeField: null,
        sizeField: null,
      },
      showTitle: true,
      title: "文本",
      name: "文本",
      type: "texts",
      w: 170,
      h: 29,
      x: 140,
      y: 61,
      z: 2,
      group: "group_hiDKMQzy",
      locked: false,
      linkage: {
        action: {
          type: "js",
          script: "",
        },
        components: [],
      },
      inParams: [],
      theme: {
        dark: {
          color: "left,#ffffff,#ffffff",
        },
        light: {
          color: "left,#ffffff,#ffffff",
        },
      },
      border: {
        type: "",
        titleHeight: 60,
        fontSize: 30,
        isTitle: true,
        padding: [0, 0, 0, 0],
      },
      expression: "return ",
      expressionCodes: [],
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      perspective: 0,
      skewX: 0,
      skewY: 0,
      customize: {
        fontSize: 20,
        fontWeight: 700,
        fontFamily: "",
        color: "left,#ffffff,#ffffff",
        title: "订单覆盖率",
        align: "center",
        letterSpacing: 1,
      },
    },
    {
      className:
        "com.gccloud.dataroom.core.module.chart.components.ScreenTextChart",
      version: "2023111401",
      key: "1719155653898",
      code: "hiDKMQzy",
      dataSource: {
        className:
          "com.gccloud.dataroom.core.module.chart.components.datasource.DataSetDataSource",
        source: "dataset",
        businessKey: "991",
        dataSourceKey: "",
        dataSetType: "1",
        params: {},
        dimensionField: "",
        metricField: "runDt",
        seriesField: "",
        dimensionFieldList: [],
        metricFieldList: [],
        seriesFieldList: [],
        serverPagination: false,
        pageSize: 10,
        colorField: null,
        shapeField: null,
        sizeField: null,
      },
      showTitle: true,
      title: "文本",
      name: "文本",
      type: "texts",
      w: 170,
      h: 29,
      x: 442,
      y: 57,
      z: 1,
      group: "group_hiDKMQzy",
      locked: false,
      linkage: {
        action: {
          type: "js",
          script: "",
        },
        components: [],
      },
      inParams: [],
      theme: {
        dark: {
          color: "left,#ffffff,#ffffff",
        },
        light: {
          color: "left,#ffffff,#ffffff",
        },
      },
      border: {
        type: "",
        titleHeight: 60,
        fontSize: 30,
        isTitle: true,
        padding: [0, 0, 0, 0],
      },
      expression: "return ",
      expressionCodes: [],
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      perspective: 0,
      skewX: 0,
      skewY: 0,
      customize: {
        fontSize: 20,
        fontWeight: 700,
        fontFamily: "",
        color: "left,#ffffff,#ffffff",
        title: "周更新：06-11",
        align: "center",
        letterSpacing: 1,
      },
    },
    {
      className:
        "com.gccloud.dataroom.core.module.chart.components.CustomComponentChart",
      version: "2023111501",
      key: "1719155413275",
      code: "MwtirszQ",
      dataSource: {
        className:
          "com.gccloud.dataroom.core.module.chart.components.datasource.DataSetDataSource",
        source: "dataset",
        businessKey: "988",
        dataSourceKey: "",
        dataSetType: "1",
        params: {},
        dimensionField: "",
        metricField: "",
        seriesField: "",
        dimensionFieldList: [],
        metricFieldList: [],
        seriesFieldList: [],
        serverPagination: false,
        pageSize: 10,
        colorField: null,
        shapeField: null,
        sizeField: null,
      },
      showTitle: true,
      title: "基础折线点图",
      name: "JiChuZheXianDianTu",
      type: "customComponent",
      w: 582,
      h: 409,
      x: 55,
      y: 43,
      z: 0,
      group: "group_hiDKMQzy",
      locked: false,
      linkage: {
        action: {
          type: "js",
          script: "",
        },
        components: [],
      },
      inParams: [],
      theme: {
        dark: {
          point_style_fill: "#6B74E4",
          label_style_fill: "#e9e9e9",
          lineStyle_stroke: "l(0) 0:#6b74e4 1:#6b74e4",
          yAxis_grid_line_style_stroke: "#E5E6EB10",
          xAxis_title_style_fill: "#e9e9e9",
          xAxis_label_style_fill: "#e9e9e9",
          xAxis_line_style_stroke: "#C9CDD4",
          xAxis_tickLine_style_stroke: "#C9CDD4",
          yAxis_title_style_fill: "#e9e9e9",
          yAxis_label_style_fill: "#e9e9e9",
          yAxis_line_stroke: "#C9CDD4",
        },
        light: {
          point_style_fill: "#6B74E4",
          label_style_fill: "#e9e9e9",
          lineStyle_stroke: "l(0) 0:#6b74e4 1:#6b74e4",
          yAxis_grid_line_style_stroke: "#E5E6EB10",
          xAxis_title_style_fill: "#e9e9e9",
          xAxis_label_style_fill: "#e9e9e9",
          xAxis_line_style_stroke: "#C9CDD4",
          xAxis_tickLine_style_stroke: "#C9CDD4",
          yAxis_title_style_fill: "#e9e9e9",
          yAxis_label_style_fill: "#e9e9e9",
          yAxis_line_stroke: "#C9CDD4",
        },
      },
      border: {
        type: "",
        titleHeight: 60,
        fontSize: 16,
        isTitle: true,
        padding: [16, 16, 16, 16],
      },
      expression: null,
      expressionCodes: null,
      rotateX: 0,
      rotateY: 0,
      rotateZ: 0,
      perspective: 0,
      skewX: 0,
      skewY: 0,
      parentCode: null,
      optionHandler:
        "\noption.yAxis.grid.line.style.lineDash = [4,setting.find(settingItem=>settingItem.field === 'yAxis_grid_line_style_lineDash').value]\nlet autoHide = setting.find(settingItem=>settingItem.field === 'xAxis_label_autoHide').value\nif(autoHide){\n  let minGap = option.xAxis.label.autoHideMinGap\n  option.xAxis.label.autoHide = {\n    type: 'equidistance',\n    cfg: { minGap: minGap }\n  }\n} else {\n  option.xAxis.label.autoHide = false\n}\n  ",
      dataHandler: "",
      chartType: "Line",
      option:
        '{"dataKey":"data","appendPadding":[0,0,0,0],"data":[],"xField":"field1","yField":"runDt","label":{"style":{"fill":"#e9e9e9","fontSize":0}},"point":{"size":3,"shape":"circle","style":{"fill":"#6B74E4","stroke":"#5B8FF9","lineWidth":2}},"tooltip":{"showMarkers":false},"state":{"active":{"style":{"shadowBlur":4,"stroke":"#000","fill":"red"}}},"lineStyle":{"lineWidth":2,"stroke":"l(0) 0:#6b74e4 1:#6b74e4"},"xAxis":{"title":{"text":"","position":"end","style":{"fill":"#e9e9e9","fontSize":12}},"label":{"autoRotate":true,"autoHide":{"type":"equidistance","cfg":{"minGap":0}},"autoEllipsis":false,"autoHideEnable":true,"autoHideMinGap":0,"style":{"fill":"#e9e9e9","fontSize":12}},"line":{"style":{"stroke":"#C9CDD4","lineWidth":1}},"tickLine":{"style":{"stroke":"#C9CDD4","lineWidth":1}}},"yAxis":{"title":{"text":"","position":"end","autoRotate":true,"style":{"fill":"#e9e9e9","fontSize":12}},"grid":{"line":{"style":{"stroke":"#E5E6EB10","lineWidth":1,"lineDash":[4,0],"strokeOpacity":0.7}}},"label":{"style":{"fill":"#e9e9e9","fontSize":12,"opacity":1}},"line":{"style":{"stroke":"#C9CDD4","lineWidth":0}}},"interactions":[{"type":"marker-active"}],"displayOption":{"serverPagination":{"enable":false},"pageSize":{"enable":false},"metricField":{"label":"指标","enable":true,"multiple":true},"dimensionField":{"label":"维度","enable":true,"multiple":true},"dimensionList":{"label":"维度","enable":false,"multiple":true},"seriesField":{"enable":false,"required":true},"dataAllocation":{"enable":true},"params":{"enable":true},"dataSourceType":{"enable":true}},"theme":"transparent"}',
      setting: [
        {
          field: "xField",
          value: "",
        },
        {
          field: "yField",
          value: "runDt",
        },
        {
          field: "point_shape",
          value: "circle",
        },
        {
          field: "point_size",
          value: 3,
        },
        {
          field: "point_style_fill",
          value: "#6B74E4",
        },
        {
          field: "label_style_fontSize",
          value: 0,
        },
        {
          field: "label_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "lineStyle_lineWidth",
          value: 2,
        },
        {
          field: "lineStyle_stroke",
          value: "l(0) 0:#6b74e4 1:#6b74e4",
        },
        {
          field: "yAxis_grid_line_style_lineDash",
          value: 0,
        },
        {
          field: "yAxis_grid_line_style_lineWidth",
          value: 1,
        },
        {
          field: "yAxis_grid_line_style_stroke",
          value: "#E5E6EB10",
        },
        {
          field: "xAxis_title_text",
          value: "",
        },
        {
          field: "xAxis_title_position",
          value: "end",
        },
        {
          field: "xAxis_title_style_fontSize",
          value: 12,
        },
        {
          field: "xAxis_title_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "xAxis_label_style_fontSize",
          value: 12,
        },
        {
          field: "xAxis_label_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "xAxis_line_style_lineWidth",
          value: 1,
        },
        {
          field: "xAxis_line_style_stroke",
          value: "#C9CDD4",
        },
        {
          field: "xAxis_tickLine_style_lineWidth",
          value: 1,
        },
        {
          field: "xAxis_tickLine_style_stroke",
          value: "#C9CDD4",
        },
        {
          field: "xAxis_label_autoHide",
          value: true,
        },
        {
          field: "xAxis_label_autoHide_minGap",
          value: 0,
        },
        {
          field: "xAxis_label_autoRotate",
          value: true,
        },
        {
          field: "xAxis_label_autoEllipsis",
          value: false,
        },
        {
          field: "yAxis_title_text",
          value: "",
        },
        {
          field: "yAxis_title_autoRotate",
          value: true,
        },
        {
          field: "yAxis_title_position",
          value: "end",
        },
        {
          field: "yAxis_title_style_fontSize",
          value: 12,
        },
        {
          field: "yAxis_title_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "yAxis_label_style_opacity",
          value: 1,
        },
        {
          field: "yAxis_label_style_fontSize",
          value: 12,
        },
        {
          field: "yAxis_label_style_fill",
          value: "#e9e9e9",
        },
        {
          field: "yAxis_line_lineWidth",
          value: 0,
        },
        {
          field: "yAxis_line_stroke",
          value: "#C9CDD4",
        },
        {
          field: "appendPadding",
          value: [0, 0, 0, 0],
        },
      ],
      category: "基础折线点图",
    },
  ],
  pageTemplateId: null,
  type: "bigScreen",
  pageConfig: {
    w: 1920,
    h: 1080,
    bgColor: "#151a26",
    lightBgColor: "#f5f7fa",
    bg: null,
    lightBg: null,
    customTheme: "dark",
    opacity: 100.0,
    cacheDataSets: [],
    fitMode: "auto",
    refreshConfig: [],
  },
  isPreview: true,
  isPublish: 0,
};
